version: "3.4"
services:
  jenkins:
    container_name: jenkins
    build:
      dockerfile: Dockerfile
      context: ./
    user: root
    ports: 
      - "9090:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

